### ISSUE TITLE
brew update error

### ISSUE THREAD

**Issue by seniorGolang** [showwin/homebrew-speedtest#1]
Error: Calling 'depends_on :hg' is disabled!
Use 'depends_on "mercurial"' instead.
/usr/local/Homebrew/Library/Taps/showwin/homebrew-speedtest/speedtest.rb:11:in `<class:Speedtest>'
Please report this to the showwin/speedtest tap!
Or, even better, submit a PR to fix it!

How to fix?

**Comment by showwin** [comment]
Hello. Thank you for reporting and using [speedtest-go](https://github.com/showwin/speedtest-go) 😃 
I made a commit to fix bug: 7e0965c1f9056ced43cdac8d6f28b8b7b9df24bb

You can execute following command to upgrade.
```
brew tap showwin/speedtest
brew upgrade speedtest
```

thank you!

**Comment by showwin** [comment]
If you don't go well, please reopen this issue.
